### ISSUE TITLE
最近两天更新有故障

### ISSUE THREAD

**Issue by talzxia** [emacs-china/Spacemacs-rocks#112]
自从更新加入xterm color后出现故障，现在一直没有再更新。如何处理此故障？
font-lock-unfontify-region: Symbol's function definition is void: xterm-color-unfontify-region
b

**Comment by zilongshanren** [comment]
建议直接去 emacs-china.org 发帖，这些只讨论与 book.emacs-china.org 相关的问题。谢谢。
