### ISSUE TITLE
在()中高亮的小缺陷

### ISSUE THREAD

**Issue by huhuang03** [emacs-china/Spacemacs-rocks#117]
```
(define-advice show-paren-function (:around (fn) fix-show-paren-function)
  "Highlight enclosing parens."
  (cond ((looking-at-p "\\s(") (funcall fn))
        (t (save-excursion
             (ignore-errors (backward-up-list))
             (funcall fn)))))
```
如果我已经在`)`上了，它会将我的下一级括号高亮，应该是将本级括号高亮才对，
只过滤了`(`，没有过滤`)`。

**Comment by zilongshanren** [comment]
@huhuang03  能否提供一个截图？

**Comment by huhuang03** [comment]
我刚把代码复制到我的init.el中又好了，已经好了，怎么关issue啊。
可能是我照着敲的时候出现了某个错误，我把cond改成if改出问题来了。。

**Comment by huhuang03** [comment]
@zilongshanren 能不能先将视频上传到youtube，然后更新README.md。youtube看视频比youku好多了。

**Comment by zilongshanren** [comment]
@huhuang03 
Youtube 的社区都在这里： https://www.youtube.com/watch?v=2Q0MhOR59u8&index=21&list=PL-61yFRAEMlXDnsm3VHfrAm4oT6vVylRG

**Comment by huhuang03** [comment]
好的，谢谢！
