### ISSUE TITLE
在emacs配置文件中加入第二天-emacs也很美时执行报错

### ISSUE THREAD

**Issue by cpselvis** [emacs-china/Spacemacs-rocks#119]
链接地址：https://github.com/emacs-china/Spacemacs-rocks#emacs-也很美

报错图片：

![image](https://cloud.githubusercontent.com/assets/18289264/20704644/051447e6-b65b-11e6-8f0b-c7ea0dbcc2aa.png)

**Comment by li-xinyang** [comment]
以后有问题去社区问。这里指解决和项目相关的问题。没细看，查下句法对不对先。

**Comment by cpselvis** [comment]
问题已经发到社区了。https://emacs-china.org/t/spacemacs-rocks/1691

**Comment by a598799539** [comment]
@@@解决没？@cpselvis 我后来直接复制的这段都还是报wrong type argument symbolp

**Comment by cpselvis** [comment]
解决啦，下面的报错不用管的，可以忽略。
