### ISSUE TITLE
http://forum.emacs-china.org/t/21-emacs/51 路径重定向没起作用

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/Spacemacs-rocks#120]
http://forum.emacs-china.org/t/21-emacs/51 重定向了至 https://emacs-china.org/ ，后面的 `/t/21-emacs/51` 丢了。不知道能不能重定向的时候保存后面的路径？

假如不能或者有些麻烦的话，也可以直接把旧地址改成新地址。根据搜索结果，https://github.com/emacs-china/Spacemacs-rocks/search?q=+http%3A%2F%2Fforum.emacs-china.org&type=Issues&utf8=%E2%9C%93 ，Issue 里出现了 8 次 ` http://forum.emacs-china.org`

**Comment by zilongshanren** [comment]
@xuchunyang  目前不太清楚怎么让重定向后的 url 生效，重定向是域名解析的时候做的。

**Comment by xuchunyang** [comment]
OK

> 假如不能或者有些麻烦的话，也可以直接把旧地址改成新地址

我刚才已经改好了。
