### ISSUE TITLE
关于第七天视频中 evil-leader 生效的问题

### ISSUE THREAD

**Issue by zhcosin** [emacs-china/Spacemacs-rocks#122]
第七天的视频中配置了 evil-leader 没有马上生效的问题，我去 [cofi/evil-leader](https://github.com/cofi/evil-leader) 看了下，它的 Readme 上有一句说明:
> Note: You should enable global-evil-leader-mode before you enable evil-mode, otherwise evil-leader won’t be enabled in initial buffers (*scratch*, *Messages*, …).

这个说明我觉得还是在电子书上提一下的好，免得新手可能折腾半天发现没有效果。

**Comment by zilongshanren** [comment]
@zhcosin  你可以发个 PR 来修正这个问题呀。

**Comment by zhcosin** [comment]
已提 PR: [#123](https://github.com/emacs-china/Spacemacs-rocks/pulls)
