### ISSUE TITLE
第三天中的一个typo

### ISSUE THREAD

**Issue by CtheSky** [emacs-china/Spacemacs-rocks#124]
看教程的时候，发现了一个typo：
Day3， 626 行的地方 `comstom.el` 应该为 `custom.el`

**Comment by zilongshanren** [comment]
@CtheSky thanks, 能否提供一个 patch？

**Comment by CtheSky** [comment]
@zilongshanren 已加！

PS：教程很棒！

**Comment by jiegec** [comment]
Closed as of #131.
