### ISSUE TITLE
README 中schedule解释有误

### ISSUE THREAD

**Issue by Qquanwei** [emacs-china/Spacemacs-rocks#125]
位置: https://github.com/emacs-china/Spacemacs-rocks/blame/master/README.org#L565

C-c C-s :  应该是设置任务开始时间

**Comment by zilongshanren** [comment]
@Qquanwei 能否提供一个 path, thanks

**Comment by Qquanwei** [comment]
提交了 https://github.com/emacs-china/Spacemacs-rocks/pull/130
