### ISSUE TITLE
感谢子龙的视频教程

### ISSUE THREAD

**Issue by yanzhang0219** [emacs-china/Spacemacs-rocks#153]
看到Day15了，虽然视频有些老，有一些个别的用法已经不支持了（或过时了），但这个系列依然是中文世界能找到的最好的Emacs视频教程了。谢谢子龙的教程。
真的希望子龙可以重新润色一下这个教程，去掉过时或不支持了的部分，并更新一些新内容。

**Comment by zilongshanren** [comment]
恩，貌似可以重启一下，考虑下 Emacs Rocks 第三季

**Comment by yanzhang0219** [comment]
期待重启！

**Comment by zilongshanren** [comment]
@yanzhang0219 已经重启，欢迎观看并提宝贵意见

**Comment by yanzhang0219** [comment]
好的，谢谢告知，等有时间了一定去再看一遍支持一下。
