### ISSUE TITLE
求上传一份视频教程到Bilibili.

### ISSUE THREAD

**Issue by SyberToto** [emacs-china/Spacemacs-rocks#156]
Youtube对墙内还是不友好，墙内在线就只有youku。Youku的广告实在是太恶心人了，求上传一份教程到Bilibili。

**Comment by zilongshanren** [comment]
B站视频有了：

第一季：

https://www.bilibili.com/video/BV184411T7Ad?from=search&seid=11751673893379263906

第二季：

https://www.bilibili.com/video/BV1Dx411z7i3?from=search&seid=11751673893379263906

**Comment by SyberToto** [comment]
不好意思，之前没发现第二季。谢谢链接
