### ISSUE TITLE
Style standard?

### ISSUE THREAD

**Issue by jiegec** [emacs-china/Spacemacs-rocks#49]
1. example block or emacs lisp block? lisp block?
2. =M-x= or ~M-x~?

**Comment by li-xinyang** [comment]
这个是我在学 org 的时候写的，所以是由这样的问题（格式不统一的问题）。

我修之后我会按照 `=` 来写并使用 lisp 代码块来写配置代码

**Comment by jiegec** [comment]
可以用emacs-lisp代替lisp

**Comment by zilongshanren** [comment]
同意，统一风格还是有好处的。

**Comment by jiegec** [comment]
我:%s一下，一会pr

**Comment by li-xinyang** [comment]
已经合并，我会在之后的记录工程中遵守这套规则的。这个 Issue 我先关闭了。再次感谢 @jiegec 的提醒与 PR。 👍
