### ISSUE TITLE
Any idea on favicon?

### ISSUE THREAD

**Issue by jiegec** [emacs-china/Spacemacs-rocks#52]

**Comment by li-xinyang** [comment]
可以考虑用 Emacs China 的 Logo 做一个，我现在有一个在 http://forum.emacs-china.org/t/emacs-china-logo/25

**Comment by zilongshanren** [comment]
@jiegec  Can I close this issue now? Any updates?

**Comment by jiegec** [comment]
@zilongshanren Forgot to do that. Sorry
