### ISSUE TITLE
Quotes in verbatim in org mode are not allowed by default.

### ISSUE THREAD

**Issue by jiegec** [emacs-china/Spacemacs-rocks#66]
See README.org#871 . A workaround here: http://emacs.stackexchange.com/questions/13820/inline-verbatim-and-code-with-quotes-in-org-mode.

**Comment by jiegec** [comment]
@li-xinyang Any thoughs?

**Comment by li-xinyang** [comment]
Thanks for the reminder. I just noticed there are multiple instances of `='=` literal in the output HTML.

<del>I am not quite sure why Org-mode set this as the default setting even after reading the resource you provided. Is there any particular purpose behind this kind of behavior?</del>

<br>

> Applying Markup to Strings in org-mode
> 07 Jul 2015, by Artur Malabarba.
> Normally, org-mode ignores your attempts to markup text that starts with " or '. That’s probably a safe measure because "~/" is a very common string to write but ~ is one of Org’s markup elements.

I just found out why this is the default setting, but it still does not make sense for me to make `'` a special char inside two `=`.


I will update the build script and include the suggested solution. 

```lisp
(setq org-emphasis-regexp-components
      '("     ('\"{“”"
        "-   .,!?;''“”\")}/\\“”"
        "    \r\n,"
        "."
        1))
```

**Comment by jiegec** [comment]
Note:
```
;; This HAS to come before (require 'org)
```

**Comment by li-xinyang** [comment]
It is still not working after moving the code above `(require 'org)`.

**Comment by jiegec** [comment]
Fixed.
