### ISSUE TITLE
Reviewing Day two of README.org

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/Spacemacs-rocks#74]
> 今天我们需要将第一天关闭的自动缩进 (electric-indent-mode) 从配置文件中去除，它是 Emacs 24.4 中加入的新特性，你可以在这篇文章中找到更多关于它的内容。我们之前关闭它是因为，它存在不理想的缩进效果（在 Eli 中用分号做注释时 fancy-comment 会造成很远的缩进，其实解决方法是使用 Elisp 推荐的两个分号而不是一个 ;; ，这样就可以避免这个问题。于是我们也就将其从配置文件中删除）

1. "Eli" 是笔误么？
2. Elisp 中 `;`, `;;`, `;;;` 和 `;;;;` 各有各的用处（参见 [(elisp) Comment Tips](https://www.gnu.org/software/emacs/manual/html_node/elisp/Comment-Tips.html) ），`;` 的缩进比较奇怪是因为它应该用在代码块的右边，比如这样：

```elisp
(setq a (prog1 b                        ; Swap values of
          (setq b a)))                  ; two variables
```

> (delete-selection-mode t)

t 可以省略掉，`(delete-selection-mode)` 也行，下面有一例证（引用自原文）

> (add-hook 'emacs-lisp-mode-hook 'show-paren-mode)

这里并没有写成 `（lambda () (show-paren-mode t)）`。

另外，非要用个参数的话，用 1 好些，因为 `(delete-selection-mode nil)` 还是会开启这个 mode，用 `(delete-selection-mode -1)` 才能关闭。其实，除了负数以外均表示开启，比如：省略参数、1、t、nil。

> 下面是几个正则表达式匹配的例子，
>
> (("\\`/tmp/fol/" . text-mode)
>  ("\\.texinfo\\'" . texinfo-mode)
>  ("\\.texi\\'" . texinfo-mode)
>  ("\\.el\\'" . emacs-lisp-mode)
>  ("\\.c\\'" . c-mode)
>  ("\\.h\\'" . c-mode)
>  …)

我知道这是对的，我不明白其中的 ` 和 '， 跟 ^ 和 $ 有什么分别？顺便解释下就好了。

> C-c a 可以打开 Agenda 模式菜单并选择不同的可视方式（ r ）

括号里的 r 是指什么？

**Comment by jiegec** [comment]
（xxx-mode t）和（xxx-mode）不一样。前者turn on 后者toggle，

**Comment by jiegec** [comment]
Note that \' matches the end of a string, where as $ matches the empty string before a newline. Thus, $ may lead to unexpected behavior when dealing with filenames containing newlines. (Should be pretty rare… ;))

**Comment by li-xinyang** [comment]
1. `Eli` 是我写错了。
2. 所有文中的 Emacs Lisp 的注释均使用 `;;`。
3. 我 `(xxx-mode t)` 我马上会将文字版中的 `t` 全部换成 `1` 来统一格式。

**Comment by xuchunyang** [comment]
> （xxx-mode t）和（xxx-mode）不一样。前者turn on 后者toggle。在这里一样。我自己写了个宏来处理这个问题，用数字1和-1。

这两者是一样的（如果不一样的话，证据是什么？）

```
(delete-selection-mode)
    ⇒ t

(delete-selection-mode t)
    ⇒ t

(delete-selection-mode 'toggle)
    ⇒ nil
```
从 Lisp 调用和交互式调用，对参数的解释不一样，这里我们讨论的是前者。

> Note that \' matches the end of a string, where as $ matches the empty string before a newline. Thus, $ may lead to unexpected behavior when dealing with **filenames containing newlines**. (Should be pretty rare… ;))

清楚一些了。（引用自哪里？）

**Comment by jiegec** [comment]
引用自EmacsWiki。下面的表来自Xah Emacs。
