### ISSUE TITLE
MELPA中source为git的package怎么安装？

### ISSUE THREAD

**Issue by ziyuanjun** [emacs-china/Spacemacs-rocks#80]
**我在MELPA中发现了一些source为git的package，比如matlab-mode，下载量有8千多。之前视频讲的好像都是github的，有相应的github链接，不知道这种git的该如何处理？**

**Comment by zilongshanren** [comment]
@ziyuanjun 
只要在 melpa 里面，不管它是git 的，github 的，还是 wiki 的，都可以直接安装吧？
另外，有问题建议去新论坛，这里的 issue 主要是留给本仓库建议的，谢谢。

论坛地址： https://emacs-china.org
