### ISSUE TITLE
不推荐一下popkit吗？

### ISSUE THREAD

**Issue by Liu233w** [emacs-china/Spacemacs-rocks#81]
在[https://github.com/emacs-china/Spacemacs-rocks/blob/master/Season2/day2/Readme.org](https://github.com/emacs-china/Spacemacs-rocks/blob/master/Season2/day2/Readme.org)中
建议推荐一下国内的源，方便大陆用户安装插件
```elisp
(add-to-list 'package-archives 
    '("popkit" . "http://elpa.popkit.org/packages/"))
```
:smile:

**Comment by li-xinyang** [comment]
这个我会在下一次 PR 中添加到最开头安装插件的部分。谢谢你的建议。

**Comment by Liu233w** [comment]
不用谢(´･ω･`)



发自我的小米手机
在 Li Xinyang <notifications@github.com>，2016年5月8日 下午2:36写道：

这个我会在下一次 PR 中添加到最开头安装插件的部分。谢谢你的建议。

**Comment by zilongshanren** [comment]
现在应该是推荐 elpa.emacs-china.org 这个源了
