### ISSUE TITLE
手机浏览时侧边栏挡住正文内容

### ISSUE THREAD

**Issue by colin4124** [emacs-china/Spacemacs-rocks#85]
@geekplux  主页没有针对手机用户进行优化

**Comment by li-xinyang** [comment]
主页并没有对移动做优化，需要从 Sapceemacs 官方文档借用他们的 CSS 样式，他们的样式有做移动优化。

**Comment by geekplux** [comment]
@li-xinyang 刚去看了下 Spacemacs 官方文档的样式，应该挺好改的，我现在改一下
